// <auto-generated />
namespace InstituteOfFineArts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_mark_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_mark_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202003030607294_edit_mark_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
