// <auto-generated />
namespace InstituteOfFineArts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_required));
        
        string IMigrationMetadata.Id
        {
            get { return "202003041033010_remove_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
