// <auto-generated />
namespace InstituteOfFineArts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_enum_complete_competition_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_enum_complete_competition_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202002270917100_add_enum_complete_competition_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
